spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/servicepilot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration

app.security.jwt.secret=CHANGE_ME_TO_LONG_SECRET_AT_LEAST_256_BITS
app.security.jwt.access-token-expiration-minutes=15
app.security.jwt.refresh-token-expiration-days=30
app.security.cookie.access-token-name=SP_ACCESS_TOKEN
app.security.cookie.refresh-token-name=SP_REFRESH_TOKEN
app.security.cookie.secure=false
app.security.cookie.same-site=Lax
app.security.cookie.domain=
app.security.cookie.path=/
app.cors.allowed-origin=http://localhost:4200
